echo "SESSION_ID = 24_8_a6db_924c_1feb
PREFIX = .
STICKER_PACKNAME = aboveall
ALWAYS_ONLINE = false
RMBG_KEY = null
LANGUAG = en
WARN_LIMIT = 3
FORCE_LOGOUT = false
BRAINSHOP = 159501,6pq8dPiYt7PdqHz3
MAX_UPLOAD = 200
REJECT_CALL = false
SUDO = 989876543210
TZ = Asia/Kolkata
VPS = true
AUTO_STATUS_VIEW = false 
SEND_READ = true
AJOIN = true
DISABLE_START_MESSAGE = false
PERSONAL_MESSAGE = null" > config.env
